config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :shops, only: [:new, :create, :show, :index]
  resources :nearby_shops, only: [:index]
  root 'tops#top'

  get 'firstpage' => 'firstpages#firstpage'

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0 list-unstyled">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  

app/views/shared/_footer.html.erb
<div class="mt-auto w-full bg-orange-600">
  <div class="container mx-auto py-4 px-5 flex flex-wrap flex-col sm:flex-row items-center justify-center">
    <p class="text-sm md:text-base text-center sm:text-left text-white">© 2023 — 
      <%= link_to "投稿一覧", posts_path, { class: "ml-1 text-white hover:text-orange-400" } %>
      <span class="mx-2 text-white">|</span>
      <%= link_to "店舗一覧", shops_path, { class: "ml-1 text-white hover:text-orange-400" } %>
    </p>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="bg-orange-600 px-4 md:px-6 py-2 md:py-4 fixed top-0 w-full">
  <div class="flex items-center justify-between">
    <!-- 検索フォームを表示するためのボタン -->
    <button id="search-toggle" class="md:hidden">
      <i class="fas fa-search fa-lg"></i>
    </button>

    <div class="absolute left-1/2 transform -translate-x-1/2 text-2xl md:text-4xl font-extrabold text-white">
      Spice Gate
    </div>

    <!-- デスクトップ用の検索フォーム -->
    <div class="hidden md:block w-1/3">
      <%= render 'shared/search_form', url: posts_path, q: @q %>
    </div>

    <!-- メニュー項目 -->
    <div id="mobile-menu" class="fixed top-0 right-0 w-1/2 h-auto bg-gray-800 bg-opacity-90 transform translate-x-full transition-transform duration-300 md:flex items-center space-x-4 md:space-x-6">
      <button id="close-menu" class="absolute top-4 right-4">
        <i class="fas fa-times fa-lg"></i>
      </button>
      <ul class="w-full p-4">
        <% if current_user.present? %>
          <li class="mb-2">
            <%= link_to '投稿一覧', posts_path, class: 'text-lg font-bold text-white hover:bg-orange-700 hover:text-white px-4 py-2 rounded transition duration-300 block text-center' %>
          </li>
          <li class="mb-2">
            <%= link_to '投稿作成', new_post_path, class: 'text-lg font-bold text-white hover:bg-orange-700 hover:text-white px-4 py-2 rounded transition duration-300 block text-center' %>
          </li>
          <li class="mb-2 text-xs md:text-sm">
            <%= link_to "#{current_user.name}のステータス", user_path(current_user), class: 'text-lg font-bold text-white hover:bg-orange-700 hover:text-white px-4 py-2 rounded transition duration-300 block text-center' %>
          </li>
          <li class="mb-2">
            <%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete }, class: 'text-lg font-bold text-white hover:bg-orange-700 hover:text-white px-4 py-2 rounded transition duration-300 block text-center' %>
          </li>
        <% else %>
          <li class="mb-2">
            <%= link_to 'ユーザー登録', new_user_path, class: 'text-lg font-bold text-white hover:bg-orange-700 hover:text-white px-4 py-2 rounded transition duration-300 block text-center' %>
          </li>
          <li class="mb-2">
            <%= link_to 'ログイン', login_path, class: 'text-lg font-bold text-white hover:bg-orange-700 hover:text-white px-4 py-2 rounded transition duration-300 block text-center' %>
          </li>
        <% end %>
      </ul>
    </div>

    <!-- ハンバーガーメニューアイコン -->
    <button id="menu-toggle" class="md:hidden ml-auto">
      <i class="fas fa-bars fa-lg"></i>
    </button>
  </div>

  <!-- モバイル用の検索フォーム -->
  <div id="mobile-search" class="md:hidden fixed top-0 left-0 rigth-0 w-1/2 h-auto bg-gray-800 bg-opacity-90 transform translateX(-100%) translateY(-110%) transition-transform duration-300 transition-opacity duration-300">
    <button id="close-search" class="absolute top-4 right-4">
      <i class="fas fa-times fa-lg"></i>
    </button>
    <%= render 'shared/search_form', url: posts_path, q: @q %>
  </div>
</div>

app/views/shared/_search_form.html.erb
<%= search_form_for @q, as: :q, url: posts_path, html: { class: 'flex flex-wrap space-x-4 mt-10', method: :get } do |f| %>
  <%= f.hidden_field :m, value: 'and' %>

  <div class="flex flex-row w-full space-x-4 mb-4 items-end">
    <div class="flex flex-col w-1/3">
      <%= f.label :shop_prefecture_eq, '都道府県', class: 'mb-2 text-xs font-bold text-white' %>
      <%= f.select :shop_prefecture_eq, Post.shop_prefectures_i18n.invert.map { |key, value| [key, Post.shop_prefectures[value]] }, {}, class: 'border p-2 text-sm bg-gray-200 rounded' %>
    </div>

    <div class="flex flex-col w-1/3">
      <%= f.label :user_tolerance_eq, '辛さ耐性', class: 'mb-2 text-xs font-bold text-white' %>
      <%= f.select :user_tolerance_eq, User.tolerances_i18n.invert.map { |key, value| [key, User.tolerances[value]] }, {}, class: 'border p-2 text-sm bg-gray-200 rounded' %>
    </div>

    <div class="flex flex-col w-1/3">
      <%= f.label :spiciness_eq, 'カレーの辛さレベル', class: 'mb-2 text-xs font-bold text-white' %>
      <%= f.select :spiciness_eq, Post.spicinesses_i18n.invert.map { |key, value| [key, Post.spicinesses[value]] }, {}, class: 'border p-2 text-sm bg-gray-200 rounded' %>
    </div>
  </div>

  <div class="flex items-center space-x-4 mt-4 w-full mb-4">
    <%= f.submit t('search'), class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded text-sm' %>
    <%= link_to t('nearby_search'), nearby_shops_path, class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded text-sm' %>
  </div>
<% end %>