config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :shops, only: [:new, :create, :show, :index]
  resources :nearby_shops, only: [:index]
  root 'tops#top'

  get 'firstpage' => 'firstpages#firstpage'

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates :title, presence: true
  validates :spiciness, presence: true
  validates :curry_img, presence: true


  enum shop_prefecture: { hokkaido: 0, aomori: 1, iwate: 2, miyagi: 3, akita: 4, yamagata: 5, fukushima: 6, ibaraki: 7, tochigi: 8, gunma: 9, saitama: 10, chiba: 11, tokyo: 12, kanagawa: 13, niigata: 14, toyama: 15, ishikawa: 16, fukui: 17, yamanashi: 18, nagano: 19, gifu: 20, shizuoka: 21, aichi: 22, mie: 23, shiga: 24, kyoto: 25, osaka: 26, hyogo: 27, nara: 28, wakayama: 29, tottori: 30, shimane: 31, okayama: 32, hiroshima: 33, yamaguchi: 34, tokushima: 35, kagawa: 36, ehime: 37, kochi: 38, fukuoka: 39, saga: 40, nagasaki: 41, kumamoto: 42, oita: 43, miyazaki: 44, kagoshima: 45, okinawa: 46 }
  enum spiciness: { no_spicy: 0, slightly_spicy: 1, moderately_spicy: 2, more_than_moderate: 3, spicy: 4 }
  
  mount_uploader :curry_img, CurryImageUploader

  def self.ransackable_attributes(_auth_object = nil)
    ["shop_prefecture", "spiciness"]
  end

  def self.ransackable_associations(_auth_object = nil)
    ["shop", "user"]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:index, :show]

  # GET /posts
  def index
    @q = Post.ransack(params[:q], search_key: :q, m: 'and')
    @posts = @q.result.order(created_at: :desc).page(params[:page]).per(10)
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @shops = Shop.all
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:notice] = "投稿に成功しました"
      redirect_to posts_path
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      flash[:notice] = "投稿を更新しました"
      redirect_to @post
    else
      flash[:alert] = "投稿の更新に失敗しました"
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to posts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :shop_id, :shop_prefecture, :title, :spiciness, :curry_img)
    end

    def ensure_correct_user
      unless @post.user == current_user
        flash[:alert] = "権限がありません"
        redirect_to posts_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class="mb-4">
      <%= form.label :title, t('posts.new.title'), class: "font-semibold text-gray-800" %>
      <%= form.text_field :title, class: "border-2 border-yellow-500 px-3 py-2 w-full mt-2 rounded-lg" %>
  </div>
  <% if local_assigns[:show_shop_selection] %>
  <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-4">
    <div class="mb-2 sm:mb-0">
      <%= form.label :shop, t('posts.new.shop'), class: "font-semibold text-gray-800" %>
      <%= form.collection_select :shop_id, Shop.all, :id, :name, {}, {class: "border-2 border-yellow-500 px-3 py-2 w-full mt-2 rounded-lg"} %>
    </div>
    <div class="mt-2 sm:mt-0">
      <%= link_to t('posts.new.new_shop_link'), new_shop_path, class: "btn btn-primary bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded-full" %>
    </div>
  </div>
  <% end %>
  <div class="mb-4">
      <%= form.label :shop_prefecture, t('posts.new.shop_prefecture'), class: "font-semibold text-gray-800" %>
      <%= form.select :shop_prefecture, Post.shop_prefectures.keys.map {|k| [t("activerecord.attributes.post.shop_prefectures.#{k}"), k]}, {}, class: "border-2 border-yellow-500 px-3 py-2 w-full mt-2 rounded-lg" %>
  </div>
  <div class="mb-4">
      <%= form.label :spiciness, t('posts.new.spiciness'), class: "font-semibold text-gray-800" %>
      <%= form.select :spiciness, Post.spicinesses.keys.map {|k| [t("activerecord.attributes.post.spicinesses.#{k}"), k]}, {}, class: "border-2 border-yellow-500 px-3 py-2 w-full mt-2 rounded-lg" %>
  </div>
  <div class="mb-4">
      <%= form.label :curry_img, t('posts.new.curry_img'), class: "font-semibold text-gray-800" %>
      <%= form.file_field :curry_img, class: "border-2 border-yellow-500 px-3 py-2 w-full mt-2 rounded-lg", id: "curryImage" %>
  </div>
  <div id="curryImagePreview"></div>

  <div class="actions mt-4">
      <%= form.submit t('posts.new.submit'), class: "btn btn-primary bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded-full" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container mx-auto px-4 md:px-0 mt-16">
  <div class="text-center mb-4">
    <div class="border-2 border-yellow-500 p-4 bg-yellow-100 rounded-lg shadow-md mb-6">
      <h1 class="mb-6 text-3xl md:text-4xl font-bold text-yellow-600 tracking-wide font-mono"><%= t('posts.edit.title') %></h1>
      <%= render partial: 'form', locals: { post: @post } %>
    </div>
    <div class='text-center mt-6'>
      <%= link_to t('posts.edit.back_to_show_link'), post_path(@post), class: "text-yellow-600 hover:text-yellow-700 font-semibold tracking-wide mr-4" %>
      <%= link_to t('posts.edit.back_to_index_link'), posts_path, class: "text-yellow-600 hover:text-yellow-700 font-semibold tracking-wide" %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="flex justify-center items-center mt-6 md:mt-48 mx-auto">
  <div class="w-full md:max-w-2xl">
    <div class="text-center mb-4">
      <h1 class="text-4xl font-bold text-yellow-600 mb-6 tracking-wide font-mono"><i class="fas fa-pen"></i> <%= t('posts.index.title') %></h1>
      <%= link_to t('posts.index.new_post_link'), new_post_path, class: "btn btn-primary mb-8 bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded-full" %>

      <% if @posts.empty? %>
        <p class="text-xl text-gray-600 mb-6 font-semibold">投稿はありません</p>
      <% else %>
        <% @posts.each do |post| %>
          <div class="border-2 border-yellow-500 p-4 mb-6 mt-6 bg-yellow-100 rounded-lg shadow-md">
            <div class="flex justify-between items-center mb-2">
              <div class="text-center flex-grow">
                <h2 class="text-2xl font-bold text-yellow-600 tracking-wide font-mono inline-block">
                  <i class="fas fa-utensils"></i>
                  <%= link_to post.title, post_path(post) %>
                </h2>
              </div>
              <a href="https://twitter.com/intent/tweet?text=<%= "#{post.user.name}さんが#{post.shop.name}の#{post.title}を食べたよ！ナイスカリー！🍛" %>&url=<%= post_url(post) %>" target="_blank" rel="noopener noreferrer" class="text-blue-500 text-lg">
                <i class="fab fa-twitter"></i>
              </a>
            </div>
            <p class="text-base md:text-lg text-gray-800 mb-2 font-semibold"><i class="fas fa-user"></i> 投稿者: <%= post.user.name %></p>
            <p class="text-lg text-gray-800 mb-2 font-semibold"><i class="fas fa-store"></i> <%= t('activerecord.attributes.post.shop') %>：<%= link_to post.shop.name, shop_path(post.shop) %></p>
            <p class="text-lg text-gray-800 mb-2 font-semibold"><i class="fas fa-map-marker-alt"></i> <%= t('posts.index.shop_prefecture', shop_prefecture: t("activerecord.attributes.post.shop_prefectures.#{post.shop_prefecture}")) %></p>
            <p class="text-lg text-gray-800 mb-2 font-semibold"><i class="fas fa-pepper-hot"></i> <%= t('posts.index.spiciness', spiciness: t("activerecord.attributes.post.spicinesses.#{post.spiciness}")) %></p>
            <p class="text-lg text-gray-800 mb-2 font-semibold"><i class="fas fa-fire mr-1"></i> <%= t('activerecord.attributes.user.tolerance') %>：<%= t("activerecord.attributes.user.tolerances.#{post.user.tolerance}") %></p>
            <%= image_tag post.curry_img.url, class: "w-full h-auto rounded-lg shadow-lg" if post.curry_img.present? %>
          </div>
        <% end %>

        <%= paginate @posts, class: "mt-6 text-yellow-600 hover:text-yellow-700 font-semibold tracking-wide" %>

      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container mx-auto px-4 md:px-0 mt-16">
  <div class="text-center mb-4">
    <div class="border-2 border-yellow-500 p-4 bg-yellow-100 rounded-lg shadow-md mb-6">
      <h1 class="mb-6 text-3xl md:text-4xl font-bold text-yellow-600 tracking-wide font-mono">新規投稿</h1>
      <%= render partial: 'form', locals: { post: @post, show_shop_selection: true } %>
    </div>
    <div class='text-center mt-6'>
      <%= link_to t('posts.new.back_to_index_link'), posts_path, class: "text-yellow-600 hover:text-yellow-700 font-semibold tracking-wide" %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% set_meta_tags default_meta_tags(post: @post) %>
<div class="flex justify-center items-center mt-6 md:mt-48 mx-auto">
  <div class="w-full md:max-w-xl">
    <div class="text-center mb-4 border-2 border-yellow-500 p-4 bg-yellow-100 rounded-lg shadow-md">
      <div class="flex justify-between items-center mb-6">
        <div class="text-center flex-grow">
          <h1 class="text-3xl md:text-4xl font-bold text-yellow-600 tracking-wide font-mono inline-block">
            <i class="fas fa-utensils mr-2"></i><%= @post.title %>
          </h1>
        </div>
        <a href="https://twitter.com/intent/tweet?text=<%= "#{@post.user.name}さんが#{@post.shop.name}の#{@post.title}を食べたよ！ナイスカリー！🍛" %>&url=<%= post_url(@post) %>" target="_blank" rel="noopener noreferrer" class="text-blue-500 text-lg ml-4">
          <i class="fab fa-twitter"></i>
        </a>
      </div>
      <p class="text-base md:text-lg text-gray-800 mb-2 font-semibold"><i class="fas fa-user mr-1"></i> 投稿者: <%= @post.user.name %></p>
      <p class="text-base md:text-lg text-gray-800 mb-2 font-semibold"><i class="fas fa-map-marker-alt mr-1"></i> <%= t('activerecord.attributes.post.shop_prefecture') %>：<%= t("activerecord.attributes.post.shop_prefectures.#{@post.shop_prefecture}") %></p>
      <p class="text-base md:text-lg text-gray-800 mb-2 font-semibold"><i class="fas fa-pepper-hot mr-1"></i> <%= t('activerecord.attributes.post.spiciness') %>：<%= t("activerecord.attributes.post.spicinesses.#{@post.spiciness}") %></p>
      <p class="text-base md:text-lg text-gray-800 mb-2 font-semibold"><i class="fas fa-fire mr-1"></i> <%= t('activerecord.attributes.user.tolerance') %>：<%= t("activerecord.attributes.user.tolerances.#{@post.user.tolerance}") %></p>
      <p class="text-base md:text-lg text-gray-800 mb-2 font-semibold"><i class="fas fa-store mr-1"></i> <%= t('activerecord.attributes.post.shop') %>：<%= link_to @post.shop.name, shop_path(@post.shop) %></p>
      <%= image_tag @post.curry_img.url, class: "w-full h-auto rounded-lg shadow-lg mb-4" if @post.curry_img.present? %>

      <% if current_user == @post.user %>
        <div class="actions flex justify-center mt-4 space-x-4">
          <%= link_to t('posts.show.edit_link'), edit_post_path(@post), class: "btn btn-primary bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded-full" %>
          <%= button_to t('posts.show.delete_link'), post_path(@post), method: :delete, data: { confirm: t('posts.show.delete_confirmation') }, class: "btn btn-danger bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded-full" %>
        </div>
      <% end %>

      <div class='text-center mt-6'>
          <%= link_to t('posts.show.back_to_index_link'), posts_path, class: "text-yellow-600 hover:text-yellow-700 font-semibold tracking-wide" %>
      </div>
    </div>
  </div>
</div>